#include <avr/pgmspace.h>
extern const prog_char http_http[8];
extern const prog_char http_200[5];
extern const prog_char http_301[5];
extern const prog_char http_302[5];
extern const prog_char http_get[5];
extern const prog_char http_10[9];
extern const prog_char http_11[9];
extern const prog_char http_icy[4];
extern const prog_char http_content_type[15];
extern const prog_char http_texthtml[10];
extern const prog_char http_location[11];
extern const prog_char http_host[7];
extern const prog_char http_crnl[3];
extern const prog_char http_index_html[12];
extern const prog_char http_404_html[10];
extern const prog_char http_content_type_html[28];
extern const prog_char http_content_type_css [27];
extern const prog_char http_content_type_text[28];
extern const prog_char http_content_type_png [28];
extern const prog_char http_content_type_gif [28];
extern const prog_char http_content_type_jpg [29];
extern const prog_char http_content_type_binary[43];
extern const prog_char http_html[6];
extern const prog_char http_shtml[7];
extern const prog_char http_htm[5];
extern const prog_char http_css[5];
extern const prog_char http_png[5];
extern const prog_char http_gif[5];
extern const prog_char http_jpg[5];
extern const prog_char http_text[6];
extern const prog_char http_txt[5];
extern const prog_char http_user_agent_fields[77];
